name: messenger_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  bloc_test: ^10.0.0
  equatable: ^2.0.7
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  firebase_messaging: ^16.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
